"""
This file contains all core-collapse models
we use in our post processing and, as a 
consequence, what the user will be able to 
select in the initial/final interpolation.
Each model is a dictionary containing the 
properties of the model used by step_SN. 
"""

__authors__ = [
    "Simone Bavera <Simone.Bavera@unige.ch>",
]

MODELS = {
    "MODEL01": {
        "mechanism": "direct",
        "engine": "",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : False,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL02": {
        "mechanism": "Fryer+12-rapid",
        "engine": "",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : False,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL03": {
        "mechanism": "Fryer+12-delayed",
        "engine": "",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : False,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL04": {
        "mechanism": "Sukhbold+16-engine",
        "engine": "N20",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : False,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL05": {
        "mechanism": "Patton&Sukhbold20-engine",
        "engine": "N20",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : False,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL06": {
        "mechanism": "direct",
        "engine": "",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : True,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL07": {
        "mechanism": "Fryer+12-rapid",
        "engine": "",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : True,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL08": {
        "mechanism": "Fryer+12-delayed",
        "engine": "",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : True,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL09": {
        "mechanism": "Sukhbold+16-engine",
        "engine": "N20",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : True,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },
    "MODEL10": {
        "mechanism": "Patton&Sukhbold20-engine",
        "engine": "N20",
        "PISN": "Marchant+19",
        "ECSN": "Podsiadlowksi+04",
        "conserve_hydrogen_envelope" : True,
        "max_neutrino_mass_loss": 0.5,
        "max_NS_mass": 2.5,
        "use_interp_values": False,
        "use_profiles": True,
        "use_core_masses": False,
        "approx_at_he_depletion": False,
    },

}