# posydon documentation build configuration file, created by
# sphinx-quickstart on Thu Apr 21 14:05:08 2016.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import re
import datetime

from PSphinxTheme import utils
from posydon import __version__ as posydon_version

# Rewrite posydon_version for docs developement
#posydon_version = 'v2.0.0-dev'


# -- Project information -----------------------------------------------------

project = u'POSYDON'
copyright =f'{datetime.datetime.now().year}, Tassos Fragos'
author = u'POSYDON Collaboration'

# -- Multi-version configuration -------------------------------------------
# INJECTION GRAB START
import subprocess

# Get versions from github tags
def get_github_tags():
    '''Get the tags from the github repository
    
    Returns
    -------
    list of str
        A list of tags sorted by version, without the 'v' prefix

    '''
    try:
        # Get the tags from the github repository
        # this looks
        tags = subprocess.check_output(['git', 'tag'], universal_newlines=True).strip().split('\n')
        
        version_tags = []
        for tag in tags:
            # Skip tags that don't look like versions
            if tag.startswith('v'):
                tag_clean = tag[1:]
                version_tags.append(tag_clean)
            else:
                continue
        version_tags.sort()
        return version_tags
    
    except Exception as e:
        print(f"Error getting tags from github: {e}")
        return []

github_tags = get_github_tags()

# 2.0.0-dev needs to be removed from the list and replaced with development
github_tags.remove('2.0.0-dev')

# get a clean current version
# some old versions require the dirty tag to be removed, because files need
# to be added to compile correctly
# only allow old tag to be dirty
old_tags = ['v1.0.0', 'v1.0.4', 'v1.0.5', 'v2.0.0-pre1', 'v2.0.0-pre2']
if posydon_version.startswith('2.0.0-dev'):
    current_version = 'dev'
    posydon_version = 'development'
elif 'dirty' in posydon_version and posydon_version in old_tags:
    current_version = posydon_version.split('+')[0]
else:
    current_version = posydon_version

# absolute path to the documentation
base_url = 'https://posydon.org/POSYDON'

# get the list of versions
url_list = [f'{base_url}/{tag}' for tag in github_tags]
v1_versions = [[tag, url] for tag, url in zip(github_tags, url_list) if tag.startswith('1.')]
v2_versions = [[tag, url] for tag, url in zip(github_tags, url_list) if tag.startswith('2.')]
 
# add development version
v2_versions.append(['dev', f'{base_url}/development'])

# Versions to be shown in the version dropdown
html_context = {
  'current_version' : current_version,
  'v1_versions' : v1_versions,
  'v2_versions' : v2_versions,
}

# The short X.Y version.
version = posydon_version
# The full version, including alpha/beta/rc tags.
release = posydon_version
# INJECTION GRAB END
# -- VERSION END ---------------------------------------------------------


# -- Path setup ----------------------------------------------------------
# Point towards the posydon source code directory
# autodoc uses this to automatically generate documentation from docstrings
sys.path.insert(0, os.path.abspath('../../posydon/'))
sys.path.insert(0, os.path.abspath('../_tmp/executables/'))

# -- General configuration ------------------------------------------------
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'numpydoc',
    'sphinx.ext.githubpages',
    'sphinx.ext.duration',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'nbsphinx',
]
autodoc_preserve_defaults = True


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'p-green'

p, html_theme, needs_sphinx = utils.set_psphinxtheme(html_theme)
html_theme_path = p

# include both class and __init__ docstrings in the class documentation
autoclass_content = 'both'

# -- numpydoc -----------------------------------

# fix numpydoc autosummary
numpydoc_show_class_members = False

# use blockquotes (numpydoc>=0.8 only)
numpydoc_use_blockquotes = True

# auto-insert plot directive in examples
numpydoc_use_plots = True

# try and update the plot detection to include .show() calls
try:  # requires numpydoc >= 0.8
    from numpydoc import docscrape_sphinx
    parts = re.split('[\(\)|]', docscrape_sphinx.IMPORT_MATPLOTLIB_RE)[1:-1]
except AttributeError:
    pass
else:
    parts.extend(('fig.show()', 'plot.show()'))
    docscrape_sphinx.IMPORT_MATPLOTLIB_RE = r'\b({})\b'.format('|'.join(parts))

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# fortran_ext = ['f']
# fortran_src = '../posydon/src/'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'posydon'

# Get the current year
current_year = datetime.datetime.now().year
copyright = u'{}, Tassos Fragos'.format(current_year)
author = u'POSYDON Collaboration'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
modindex_common_prefix = ["posydon."]

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
# html_title = u'posydon v0.1'

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16
# or 32x32 pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

html_static_path = ['_static'] 
# html_static_path is added before the below files.
html_css_files = ['custom.css']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
# html_last_updated_fmt = None

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'posydondoc'

# Add logo to the sidebar
html_logo = 'posydon_logo.png'
html_theme_options = {
    'logo_only': True,
    'display_version': True,
}

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
# author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'posydon.tex', u'posydon Documentation',
     u'POSYDON Collaboration', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'posydon', u'posydon Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
# dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'posydon', u'posydon Documentation',
     author, 'posydon',
     'POSYDON: The Next Generation of Population Synthesis.', 'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

# -- Extensions -----------------------------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/', None),
    'numpy': ('https://docs.scipy.org/doc/numpy/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/reference/', None),
    'matplotlib': ('http://matplotlib.org/', None),
    'astropy': ('http://docs.astropy.org/en/stable/', None),
}

# skip jupyter notebook execution
nbsphinx_execute = 'never'
