{% set name = "posydon" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python==3.7
    - setuptools>=38.2.5

  run:
    - python==3.7
    - numpy==1.19.1
    - scipy==1.5.2
    - iminuit==1.4.9
    - configparser==5.0.0
    - pandas==1.1.0
    - scikit-learn==0.21.3
    - matplotlib==3.2.2
    - h5py==2.10.0
    - psutil==5.6.7
    - tqdm==4.48.2
    - pytables==3.6.1
    - astropy==4.0.0
    - matplotlib-label-lines>=0.3.8
    - PyQt>=5.15.3
    - progressbar2==4.0.0
    - mpi4py==3.0.3

test:
  imports:
    - posydon

about:
  home: https://github.com/POSYDON-code/POSYDON.git
  license: GPLv3+
  license_family: GPL3
