name: publish_conda

on:
  release:
    types: [published]
  pull_request:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: publish-to-conda
      uses: scottcoughlin2014/publish_conda_package_action@v1.0.0-beta
      with:
        CondaDir: 'conda'
        Platforms: 'noarch'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}
        CondaChannel: 'posydon'
