name: publish_conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: publish-to-conda
      uses: POSYDON-code/publish_to_anaconda@v1.0.1
      with:
        CondaDir: 'conda'
        Platforms: 'noarch'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}
        CondaChannel: 'posydon'
